name: build_windows

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Checkout Submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true

    - name: Checkout LFS objects
      shell: bash
      run: git lfs checkout

    - name: Build
      shell: bash
      run: |
        mkdir ./build
        cmake . -B ./build -DCMAKE_BUILD_TYPE=Release
        cmake --build ./build
