name: build_linux

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    name: ${{ matrix.config }} Linux ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [x86_64]

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Checkout Submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build
      run: |
        mkdir ./build
        cmake . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G Unix\ Makefiles
        cmake --build ./build
