name: "Linux + Clang/GCC"

on: [push, pull_request, workflow_dispatch]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - { name: "Linux + Clang x86_64", c_compiler: "clang", cpp_compiler: "clang++"}
          - { name: "Linux + gcc x86_64", c_compiler: "gcc", cpp_compiler: "g++"}

    name: ${{ matrix.config.name }}

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev

    - name: Checkout Submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout

    - name: Build
      run: |
        cmake . -B ./build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=${{ matrix.config.c_compiler }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cpp_compiler }} -G Unix\ Makefiles
        cmake --build ./build
