name: "Windows + msvc x86_64"

on: [push, pull_request, workflow_dispatch]

jobs:
  windows:
    name: "Windows + msvc x86_64"
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout Submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        lfs: true

    - name: Checkout LFS objects
      shell: bash
      run: git lfs checkout

    - name: Build
      shell: bash
      run: |
        cmake . -B ./build -DCMAKE_BUILD_TYPE=Release
        cmake --build ./build

